/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRequestsRouteImport } from './routes/ai-requests'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AssignmentHelpRouteImport } from './routes/assignment-help'
import { Route as ClassHelpRouteImport } from './routes/class-help'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ExamHelpRouteImport } from './routes/exam-help'
import { Route as ExpertsRouteImport } from './routes/experts'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StealthRouteImport } from './routes/stealth'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRequestsRoute = AiRequestsRouteImport.update({
  id: '/ai-requests',
  path: '/ai-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentHelpRoute = AssignmentHelpRouteImport.update({
  id: '/assignment-help',
  path: '/assignment-help',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassHelpRoute = ClassHelpRouteImport.update({
  id: '/class-help',
  path: '/class-help',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamHelpRoute = ExamHelpRouteImport.update({
  id: '/exam-help',
  path: '/exam-help',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsRoute = ExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StealthRoute = StealthRouteImport.update({
  id: '/stealth',
  path: '/stealth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-requests': typeof AiRequestsRoute
  '/analytics': typeof AnalyticsRoute
  '/assignment-help': typeof AssignmentHelpRoute
  '/class-help': typeof ClassHelpRoute
  '/customers': typeof CustomersRoute
  '/exam-help': typeof ExamHelpRoute
  '/experts': typeof ExpertsRoute
  '/materials': typeof MaterialsRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/stealth': typeof StealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-requests': typeof AiRequestsRoute
  '/analytics': typeof AnalyticsRoute
  '/assignment-help': typeof AssignmentHelpRoute
  '/class-help': typeof ClassHelpRoute
  '/customers': typeof CustomersRoute
  '/exam-help': typeof ExamHelpRoute
  '/experts': typeof ExpertsRoute
  '/materials': typeof MaterialsRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/stealth': typeof StealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-requests': typeof AiRequestsRoute
  '/analytics': typeof AnalyticsRoute
  '/assignment-help': typeof AssignmentHelpRoute
  '/class-help': typeof ClassHelpRoute
  '/customers': typeof CustomersRoute
  '/exam-help': typeof ExamHelpRoute
  '/experts': typeof ExpertsRoute
  '/materials': typeof MaterialsRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/stealth': typeof StealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-requests'
    | '/analytics'
    | '/assignment-help'
    | '/class-help'
    | '/customers'
    | '/exam-help'
    | '/experts'
    | '/materials'
    | '/orders'
    | '/payments'
    | '/settings'
    | '/stealth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-requests'
    | '/analytics'
    | '/assignment-help'
    | '/class-help'
    | '/customers'
    | '/exam-help'
    | '/experts'
    | '/materials'
    | '/orders'
    | '/payments'
    | '/settings'
    | '/stealth'
  id:
    | '__root__'
    | '/'
    | '/ai-requests'
    | '/analytics'
    | '/assignment-help'
    | '/class-help'
    | '/customers'
    | '/exam-help'
    | '/experts'
    | '/materials'
    | '/orders'
    | '/payments'
    | '/settings'
    | '/stealth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRequestsRoute: typeof AiRequestsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssignmentHelpRoute: typeof AssignmentHelpRoute
  ClassHelpRoute: typeof ClassHelpRoute
  CustomersRoute: typeof CustomersRoute
  ExamHelpRoute: typeof ExamHelpRoute
  ExpertsRoute: typeof ExpertsRoute
  MaterialsRoute: typeof MaterialsRoute
  OrdersRoute: typeof OrdersRoute
  PaymentsRoute: typeof PaymentsRoute
  SettingsRoute: typeof SettingsRoute
  StealthRoute: typeof StealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-requests': {
      id: '/ai-requests'
      path: '/ai-requests'
      fullPath: '/ai-requests'
      preLoaderRoute: typeof AiRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignment-help': {
      id: '/assignment-help'
      path: '/assignment-help'
      fullPath: '/assignment-help'
      preLoaderRoute: typeof AssignmentHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class-help': {
      id: '/class-help'
      path: '/class-help'
      fullPath: '/class-help'
      preLoaderRoute: typeof ClassHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-help': {
      id: '/exam-help'
      path: '/exam-help'
      fullPath: '/exam-help'
      preLoaderRoute: typeof ExamHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts': {
      id: '/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof ExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stealth': {
      id: '/stealth'
      path: '/stealth'
      fullPath: '/stealth'
      preLoaderRoute: typeof StealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRequestsRoute: AiRequestsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssignmentHelpRoute: AssignmentHelpRoute,
  ClassHelpRoute: ClassHelpRoute,
  CustomersRoute: CustomersRoute,
  ExamHelpRoute: ExamHelpRoute,
  ExpertsRoute: ExpertsRoute,
  MaterialsRoute: MaterialsRoute,
  OrdersRoute: OrdersRoute,
  PaymentsRoute: PaymentsRoute,
  SettingsRoute: SettingsRoute,
  StealthRoute: StealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
